#!/bin/sh
set -eu
if [ "${1:-}" = remove ]; then
  systemctl stop personenzaehler-api.service personenzaehler.service >/dev/null 2>&1 || true
  systemctl disable personenzaehler-api.service personenzaehler.service >/dev/null 2>&1 || true
fi
exit 0
